export type Book = {
  title: string;
  author: string;
  label?: string;
  status: string;
  description: string;
  isbn: string;
  spine: string;
  cover: string;
  lightSpine?: boolean;
};

export const books: Book[] = [
  {
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    status: "Reading",
    description: "The big ideas behind reliable, scalable, and maintainable systems.",
    isbn: "9781449373320",
    spine: "#b42318",
    cover: "#7f1d1d",
  },
  {
    title: "Database Internals",
    author: "Alex Petrov",
    status: "Reading",
    description: "A deep dive into how distributed data systems work under the hood.",
    isbn: "9781492040347",
    spine: "#e7e2d6",
    cover: "#1c1917",
    lightSpine: true,
  },
  {
    title: "Clean Architecture",
    author: "Robert C. Martin",
    status: "Completed",
    description: "A craftsman's guide to software structure and design.",
    isbn: "9780134494166",
    spine: "#1e3a5f",
    cover: "#0f172a",
  },
  {
    title: "Readings in Database Systems",
    author: "Joseph M. Hellerstein & Michael Stonebraker",
    label: "Hellerstein",
    status: "On the shelf",
    description: "The red book: classic papers on how database systems are actually built.",
    isbn: "9780262693141",
    spine: "#9f1239",
    cover: "#4c0519",
  },
  {
    title: "Computer Systems: A Programmer's Perspective",
    author: "Randal E. Bryant & David R. O'Hallaron",
    label: "Bryant",
    status: "On the shelf",
    description: "How programs run, from bits and caches down to the operating system.",
    isbn: "9780134092669",
    spine: "#c2410c",
    cover: "#7c2d12",
  },
  {
    title: "Elon Musk",
    author: "Walter Isaacson",
    status: "On the shelf",
    description: "Isaacson's biography of Elon Musk.",
    isbn: "9781982181284",
    spine: "#171717",
    cover: "#0a0a0a",
  },
  {
    title: "Mastery",
    author: "Robert Greene",
    status: "On the shelf",
    description: "How apprenticeship, practice, and attention turn into mastery.",
    isbn: "9780670024964",
    spine: "#1c1917",
    cover: "#292524",
  },
  {
    title: "Hackers & Painters",
    author: "Paul Graham",
    status: "On the shelf",
    description: "Essays on making things, from programming to painting.",
    isbn: "9780596006624",
    spine: "#f4efe4",
    cover: "#e7e5e4",
    lightSpine: true,
  },
  {
    title: "The Art of Doing Science and Engineering",
    author: "Richard Hamming",
    label: "Hamming",
    status: "On the shelf",
    description: "Hamming on how to do the work that matters.",
    isbn: "9781732265172",
    spine: "#1e293b",
    cover: "#0f172a",
  },
  {
    title: "Writing A Compiler In Go",
    author: "Thorsten Ball",
    label: "Ball",
    status: "On the shelf",
    description: "A walk through building a compiler, written in Go.",
    isbn: "9783982016108",
    spine: "#eab308",
    cover: "#171717",
    lightSpine: true,
  },
  {
    title: "How to Solve It",
    author: "George Pólya",
    label: "Pólya",
    status: "On the shelf",
    description: "A short, practical guide to attacking problems you don't yet know how to solve.",
    isbn: "9780691164076",
    spine: "#f5d76e",
    cover: "#a16207",
    lightSpine: true,
  },
  {
    title: "How to Prove It",
    author: "Daniel J. Velleman",
    label: "Velleman",
    status: "On the shelf",
    description: "A structured introduction to mathematical proof.",
    isbn: "9781108439534",
    spine: "#1d4ed8",
    cover: "#1e3a8a",
  },
  {
    title: "Concurrency in Go",
    author: "Katherine Cox-Buday",
    label: "Cox-Buday",
    status: "On the shelf",
    description: "Tools and patterns for writing concurrent programs in Go.",
    isbn: "9781491941195",
    spine: "#1e3a4c",
    cover: "#0c4a6e",
  },
];
